# Generated by Django 5.1.1 on 2024-10-05 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='list_model',
            name='prioritet',
            field=models.CharField(default='Средний', max_length=20),
        ),
    ]
