# Generated by Django 5.1.1 on 2024-10-06 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_list_model_prioritet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list_model',
            name='prioritet',
            field=models.CharField(choices=[('Высокий', 'High'), ('Средний', 'Mid'), ('Низкий', 'Low')], max_length=20),
        ),
    ]
