# Generated by Django 5.1.1 on 2024-10-08 11:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_list_model_prioritet'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='list_model',
            name='prioritet',
            field=models.CharField(choices=[('High', 'Высокий'), ('Mid', 'Средний'), ('Low', 'Низкий')], max_length=20),
        ),
        migrations.AlterField(
            model_name='list_model',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
