# Generated by Django 5.1.1 on 2024-10-08 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_alter_list_model_prioritet_alter_list_model_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list_model',
            name='date_finish',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='list_model',
            name='date_start',
            field=models.DateField(),
        ),
    ]
