# Generated by Django 5.1.1 on 2024-10-09 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_alter_list_model_date_finish_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list_model',
            name='date_finish',
            field=models.DateField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='list_model',
            name='date_start',
            field=models.DateField(blank=True, default=None),
        ),
    ]
